name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn doc
    - run: cp ./docs/index.html ./docs/200.html
    - name: Deploy doc
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'docs.canalmultiply.surge.sh'
        project: './docs'
        login: ${{ secrets.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_TOKEN }}

  story:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn build-storybook
    - run: cp ./storybook-static/index.html ./storybook-static/200.html
    - name: Deploy storybook
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'story.canalmultiply.surge.sh'
        project: './storybook-static'
        login: ${{ secrets.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - run: yarn --frozen-lockfile
    - run: yarn build
    - run: cp ./dist/index.html ./dist/200.html
    - name: Deploy build
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'canalmultiply.surge.sh'
        project: './dist'
        login: ${{ secrets.SURGE_LOGIN }}
        token: ${{ secrets.SURGE_TOKEN }}

